### ISSUE TITLE
Can you please confirm if this project is still usable?

### ISSUE THREAD

**Issue by halace** [teiid/teiid-extensions#56]
We are planning to log our command logs to database. Can I use this project as mentioned in Readme?

**Comment by rareddy** [comment]
you can, but we will not be adding any modifications

**Comment by halace** [comment]
Hello Ramesh,

I am getting the following error while compiling using maven clean install

$ /c/DataVirtualization/apache-maven-3.6.3/bin/mvn clean install
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/jboss/integration-platform/jboss-integration-platform-parent/6.0.0.CR30/jboss-integration-platform-parent-6.0.0.CR30.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/jboss/integration-platform/jboss-integration-platform-parent/6.0.0.CR30/jboss-integration-platform-parent-6.0.0.CR30.pom (25 kB at 35 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/jboss-parent/16/jboss-parent-16.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/jboss-parent/16/jboss-parent-16.pom (32 kB at 27 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/integration-platform/jboss-integration-platform-bom/6.0.0.CR30/jboss-integration-platform-bom-6.0.0.CR30.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/integration-platform/jboss-integration-platform-bom/6.0.0.CR30/jboss-integration-platform-bom-6.0.0.CR30.pom (109 kB at 196 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/arquillian/selenium/selenium-bom/2.46.0/selenium-bom-2.46.0.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/arquillian/selenium/selenium-bom/2.46.0/selenium-bom-2.46.0.pom (5.2 kB at 14 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.2.0/shrinkwrap-resolver-bom-2.2.0.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.2.0/shrinkwrap-resolver-bom-2.2.0.pom (5.3 kB at 13 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/arquillian/arquillian-bom/1.1.9.Final/arquillian-bom-1.1.9.Final.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/arquillian/arquillian-bom/1.1.9.Final/arquillian-bom-1.1.9.Final.pom (11 kB at 26 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/shrinkwrap-bom/1.2.2/shrinkwrap-bom-1.2.2.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/shrinkwrap-bom/1.2.2/shrinkwrap-bom-1.2.2.pom (4.0 kB at 11 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.1.1/shrinkwrap-resolver-bom-2.1.1.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.1.1/shrinkwrap-resolver-bom-2.1.1.pom (4.6 kB at 11 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-bom/2.0.0-alpha-7/shrinkwrap-descriptors-bom-2.0.0-alpha-7.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/shrinkwrap/descriptors/shrinkwrap-descriptors-bom/2.0.0-alpha-7/shrinkwrap-descriptors-bom-2.0.0-alpha-7.pom (5.2 kB at 12 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/springframework/spring-framework-bom/3.2.12.RELEASE/spring-framework-bom-3.2.12.RELEASE.pom
Downloaded from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/springframework/spring-framework-bom/3.2.12.RELEASE/spring-framework-bom-3.2.12.RELEASE.pom (4.8 kB at 11 kB/s)
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/teiid/teiid-parent/8.12.11.6_4/teiid-parent-8.12.11.6_4.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/jboss/teiid/teiid-parent/8.12.11.6_4/teiid-parent-8.12.11.6_4.pom
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/bom/eap/jboss-javaee-6.0-with-tools/6.4.4.GA/jboss-javaee-6.0-with-tools-6.4.4.GA.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/jboss/bom/eap/jboss-javaee-6.0-with-tools/6.4.4.GA/jboss-javaee-6.0-with-tools-6.4.4.GA.pom
Downloading from jboss-public-repository-group: http://repository.jboss.org/nexus/content/groups/public/org/jboss/bom/eap/jboss-javaee-6.0-with-hibernate/6.4.4.GA/jboss-javaee-6.0-with-hibernate-6.4.4.GA.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/jboss/bom/eap/jboss-javaee-6.0-with-hibernate/6.4.4.GA/jboss-javaee-6.0-with-hibernate-6.4.4.GA.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.teiid:teiid-parent:pom:8.12.11.6_4 in jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/) @ line 92, column 16
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.4.GA in jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/) @ line 100, column 25
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.4.GA in jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/) @ line 107, column 25
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jboss.teiid:extensions:1.3.0 (C:\Users\halace\Documents\GitHub\teiid-extensions\pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.teiid:teiid-parent:pom:8.12.11.6_4 in jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/) @ line 92, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.4.GA in jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/) @ line 100, column 25 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.4.GA in jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/) @ line 107, column 25 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException


Is the version mentioned in pom.xml correct or need a revision?
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.org.jboss.integration-platform>6.0.0.CR30</version.org.jboss.integration-platform>
        
        <version.jboss.bom>6.4.4.GA</version.jboss.bom>
        <version.teiid.project>8.12.11.6_4</version.teiid.project>

        <jbossas-module-root>modules/system/layers/dv</jbossas-module-root>

    	
        <db.jarloc>dataVirtualization/logging</db.jarloc>
        <cli.scriploc>/cli-scripts</cli.scriploc>
 
    </properties>
